spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081